### ISSUE TITLE
Incorrect .pyi output for namedtuple() base class.

### ISSUE THREAD

**Issue by mrolle45** [google/pytype#1152]
My module `solver.modifiers.py` contains the following:
```
class Mod(namedtuple('Mod', 'key, info')):
    ...
```
After running `pytype` as an infer, `modifier.pyi` has the following:
```
namedtuple_Mod_key_info: Type[solver.modifiers.namedtuple_Mod_key_info]
...
class Mod(Any):       # This is OK except for the `Any` base class
    ...
```
This module is referenced by module `solver.instruct.py` through a chain of imports.  `imports/solver.instruct.imports` has the line:
```
solver/modifiers /mnt/d/Solutions/trunk/Python/Sass/.pytype/pyi/solver/modifiers.pyi-1
```
Its `.pyi` file appears correct, including a definition:
```
Mod: Type[solver.modifiers.Mod]
```

A third module, `solver.opcodes` references both of these.  After running `pytype` in infer mode, `solver/opcodes.pyi` contains the following, in its entirety:
```

from typing import Any
def __getattr__(name: Any) -> Any: ...
# Caught error in pytype: Unreplaced NamedType: 'solver.modifiers.namedtuple_Mod_key_info', referenced from 'solver.instruct'
# Traceback (most recent call last):
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 337, in verify
#     mod_ast.Visit(visitors.VerifyLookup(ignore_late_types=True))
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 99, in Visit
#     return _Visit(self, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 117, in _Visit
#     return _VisitNode(node, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 168, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 168, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 191, in _VisitNode
#     status = visitor.Enter(node, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/base_visitor.py", line 199, in Enter
#     return self.enter_functions[node.__class__.__name__](
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/visitors.py", line 227, in EnterNamedType
#     raise ValueError("Unreplaced NamedType: %r" % node.name)
# ValueError: Unreplaced NamedType: 'solver.modifiers.namedtuple_Mod_key_info'
# 
# The above exception was the direct cause of the following exception:
# 
# Traceback (most recent call last):
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 610, in finish_and_verify_ast
#     self._resolver.verify(mod_ast)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 340, in verify
#     raise BadDependencyError(utils.message(e), name) from e
# pytype.load_pytd.BadDependencyError: Unreplaced NamedType: 'solver.modifiers.namedtuple_Mod_key_info', referenced from 'solver.instruct'
# 
# During handling of the above exception, another exception occurred:
# 
# Traceback (most recent call last):
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 337, in verify
#     mod_ast.Visit(visitors.VerifyLookup(ignore_late_types=True))
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 99, in Visit
#     return _Visit(self, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 117, in _Visit
#     return _VisitNode(node, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 168, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 168, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 191, in _VisitNode
#     status = visitor.Enter(node, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/base_visitor.py", line 199, in Enter
#     return self.enter_functions[node.__class__.__name__](
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/visitors.py", line 227, in EnterNamedType
#     raise ValueError("Unreplaced NamedType: %r" % node.name)
# ValueError: Unreplaced NamedType: 'solver.modifiers.namedtuple_Mod_key_info'
# 
# The above exception was the direct cause of the following exception:
# 
# Traceback (most recent call last):
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/io.py", line 148, in check_or_generate_pyi
#     errorlog, result, ast = generate_pyi(
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/io.py", line 107, in generate_pyi
#     errorlog, (mod, builtins) = _call(analyze.infer_types, src, options, loader)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/io.py", line 60, in wrapper
#     return f(*args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/io.py", line 73, in _call
#     return errorlog, analyze_types(
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/analyze.py", line 90, in infer_types
#     loc, defs = ctx.vm.run_program(src, filename, init_maximum_depth)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/vm.py", line 423, in run_program
#     node, f_globals, f_locals, _ = self.run_bytecode(node, code)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/vm.py", line 385, in run_bytecode
#     node, return_var = self.run_frame(frame, node)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/vm.py", line 232, in run_frame
#     state = self.run_instruction(op, state)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/vm.py", line 200, in run_instruction
#     state = bytecode_fn(state, op)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/vm.py", line 2409, in byte_IMPORT_STAR
#     for name, var in mod.items():
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/abstract/_instances.py", line 120, in items
#     self.load_lazy_attribute(name)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/abstract/mixin.py", line 225, in load_lazy_attribute
#     variable = self._convert_member(self._member_map[name], subst)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/abstract/_instances.py", line 59, in _convert_member
#     var = self.ctx.convert.constant_to_var(member)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/convert.py", line 397, in constant_to_var
#     return self.constant_to_var(pyval.type, subst, node, source_sets,
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/convert.py", line 432, in constant_to_var
#     result = self.constant_to_value(pyval, subst, node)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/convert.py", line 492, in constant_to_value
#     value = self._constant_to_value(pyval, subst, get_node)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/convert.py", line 626, in _constant_to_value
#     mod = self.ctx.loader.import_name(pyval.module_name)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 602, in import_name
#     mod_ast = self.finish_and_verify_ast(mod_ast)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 616, in finish_and_verify_ast
#     self._resolver.verify(mod_ast)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 340, in verify
#     raise BadDependencyError(utils.message(e), name) from e
# pytype.load_pytd.BadDependencyError: Unreplaced NamedType: 'solver.modifiers.namedtuple_Mod_key_info', referenced from 'solver.instruct'
```

**The errors**
1. Creating the incorrect name `namedtuple_Mod_key_info`
2. Incorrect base class in `class Mod(Any):`
3. Crash running inference, shown above.

**Workarounds**
I will use `@attrs.define` decorator for the `Mods` class instead of `namedtuple`.  I prefer that style anyway.
You might want to try my example with a list `['key', 'info']` or `'key, info'.split(", ")` or  `'key info'.split()`

**Comment by mrolle45** [comment]
I did not find a way to label this issue as a bug.  Could somebody do that for me, please, unless you all haven't gotten around to creating categories for issues.

**Comment by rchen152** [comment]
I believe this should be fixed in the latest release! We refactored our NamedTuple-generating code to stop depending on intermediate classes.
