### ISSUE TITLE
merge_pyi crashes with keyword-only args in function def.

### ISSUE THREAD

**Issue by mrolle45** [google/pytype#1153]
_Note: I have included a patch to the code that fixes this bug, but as I am not familiar with pull requests and tests, I would like some reader **to apply this patch**.  Thanks._

The source of the function def is
```
def foo(self, *, kwd: bool = False) -> int:
	return 42
```
The exception traceback:
```
Traceback (most recent call last):
  File "D:\Solutions\trunk\Python\Pytype\pytype\tools\merge_pyi\main.py", line 101, in <module>
    main()
  File "D:\Solutions\trunk\Python\Pytype\pytype\tools\merge_pyi\main.py", line 82, in main
    annotated_src = merge_pyi.annotate_string(args, py_src, pyi_src)
  File "D:\Solutions\trunk\Python\Pytype\pytype\tools\merge_pyi\merge_pyi.py", line 928, in annotate_string
    tree = tool.refactor_string(py_src + '\n', '<inline>')
  File "D:\Python37\lib\lib2to3\refactor.py", line 367, in refactor_string
    self.refactor_tree(tree, name)
  File "D:\Python37\lib\lib2to3\refactor.py", line 441, in refactor_tree
    new = fixer.transform(node, results)
  File "D:\Solutions\trunk\Python\Pytype\pytype\tools\merge_pyi\merge_pyi.py", line 518, in transform
    src_sig = FuncSignature(node, results)
  File "D:\Solutions\trunk\Python\Pytype\pytype\tools\merge_pyi\merge_pyi.py", line 306, in __init__
    self._arg_sigs = tuple(map(ArgSignature, args))
  File "D:\Solutions\trunk\Python\Pytype\pytype\tools\merge_pyi\merge_pyi.py", line 123, in __init__
    sig = ArgSignature._split_arg(arg_nodes)
  File "D:\Solutions\trunk\Python\Pytype\pytype\tools\merge_pyi\merge_pyi.py", line 240, in _split_arg
    raise KnownError()  # expected/parse_error.py
pytype.tools.merge_pyi.merge_pyi.KnownError
```
**The bug**
`_split_arg` is not prepared for a Texan input (i.e. lone star :) ).  It receives an arg list with only the `"*"` leaf.
After stripping off this leaf, the arg list is now empty.

**Proposed fix**
In this case, make a return with the '*' as `stars`, and an empty `arg`.  Further processing is not harmed by this.
Here is the change I made to `_split_arg` lines 239-240:
```
    if len(arg) != 1:
      if not arg and stars == '*':                                  # added
        return is_tuple, stars, arg_type, arg, default              # added
      raise KnownError()  # expected/parse_error.py
```
Here is the resulting output, using unannotated function def in the .pyi file:
```
def foo(self, *, kwd: bool = False) -> int:
        return 42
```

_FYI:_ Here is a pretty-print I made of the parse tree used in this example:
```
Node(funcdef)
:   Leaf(1, 'def')
:   Leaf(1, 'foo')
:   Node(parameters)
:   :   Leaf(7, '(')
:   :   Node(typedargslist)
:   :   :   Leaf(1, 'self')
:   :   :   Leaf(12, ',')
:   :   :   Leaf(16, '*')
:   :   :   Leaf(12, ',')
:   :   :   Node(tname)
:   :   :   :   Leaf(1, 'kwd')
:   :   :   :   Leaf(11, ':')
:   :   :   :   Leaf(1, 'bool')
:   :   :   Leaf(22, '=')
:   :   :   Leaf(1, 'False')
:   :   Leaf(8, ')')
:   Leaf(55, '->')
:   Leaf(1, 'int')
:   Leaf(11, ':')
:   Node(suite)
:   :   Leaf(4, '\n')
:   :   Leaf(5, '\t')
:   :   Node(simple_stmt)
:   :   :   Node(return_stmt)
:   :   :   :   Leaf(1, 'return')
:   :   :   :   Leaf(2, '42')
:   :   :   Leaf(4, '\n')
:   :   Leaf(6, '')```
```

**Comment by martindemello** [comment]
thanks! we are currently rewriting merge_pyi completely on top of libcst, but will apply this patch in the mean time so that it's a bit more usable.
