### ISSUE TITLE
pytype crash when processing "type(NamedTuple)"

### ISSUE THREAD

**Issue by mrolle45** [google/pytype#1171]
I have a module, which I have boiled down to this example:
```
cache.py:
""" A utility module to create a cache of objects by constructor parameters. """
from __future__ import annotations
from typing import NamedTuple
T = type(NamedTuple)
```

I run pytype with the command:
`pytype-single cache.py -o .pytype/pyi/cache.pyi --quick --no-report-errors --nofail`

The output file contains:
```

from typing import Any
def __getattr__(name: Any) -> Any: ...
# Caught error in pytype: No NamedTuple in module typing, referenced from 'inferred + unknowns'
# Traceback (most recent call last):
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/visitors.py", line 445, in VisitNamedType
#     item = pytd.LookupItemRecursive(module, name)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/pytd.py", line 790, in LookupItemRecursive
#     raise KeyError(item)
# KeyError: TypeDeclUnit(name='typing', constants=(Constant(name='typing.TYPE_CHECKING',  ... much more 
# 
# The above exception was the direct cause of the following exception:
# 
# Traceback (most recent call last):
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 316, in resolve_external_types
#     mod_ast = mod_ast.Visit(visitors.LookupExternalTypes(
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 99, in Visit
#     return _Visit(self, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 117, in _Visit
#     return _VisitNode(node, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 168, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 168, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 168, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 209, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 168, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 222, in _VisitNode
#     new_node = visitor.Visit(new_node, *args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/base_visitor.py", line 203, in Visit
#     return self.visit_functions[node.__class__.__name__](
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/pytd/visitors.py", line 454, in VisitNamedType
#     raise KeyError("No %s in module %s" % (name, module_name)) from e
# KeyError: 'No NamedTuple in module typing'
# 
# The above exception was the direct cause of the following exception:
# 
# Traceback (most recent call last):
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/io.py", line 147, in check_or_generate_pyi
#     errorlog, result, ast = generate_pyi(
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/io.py", line 106, in generate_pyi
#     errorlog, (mod, builtins) = _call(analyze.infer_types, src, options, loader)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/io.py", line 60, in wrapper
#     return f(*args, **kwargs)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/io.py", line 72, in _call
#     return errorlog, analyze_types(
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/analyze.py", line 108, in infer_types
#     ast = ctx.loader.resolve_ast(ast)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 554, in resolve_ast
#     return self.resolve_pytd(ast, ast)
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 544, in resolve_pytd
#     pytd_node = self._resolve_external_and_local_types(
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 406, in _resolve_external_and_local_types
#     mod_ast = self._resolve_external_types(
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 530, in _resolve_external_types
#     mod_ast = self._resolver.resolve_external_types(
#   File "/home/michael/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 319, in resolve_external_types
#     raise BadDependencyError(utils.message(e), name) from e
# pytype.load_pytd.BadDependencyError: No NamedTuple in module typing, referenced from 'inferred + unknowns'
```
I am running version 2022.03.08 on Ubuntu via Windows WSL.

**Comment by mrolle45** [comment]
If I change the input module to:
```
""" A utility module to create a cache of objects by constructor parameters. """
from __future__ import annotations
from typing import NamedTuple
T = NamedTuple.__class__
```
then the output is
```
# (generated with --quick)

import __future__
from typing import Type

T: Type[type]
annotations: __future__._Feature
```
This shows that it is the expression `type(NamedTuple)` that is the cause of the crash.

**Comment by rchen152** [comment]
We definitely shouldn't crash, but FYI, I wouldn't recommend using `type(NamedTuple)` in your code. Starting in Python 3.9, typing.NamedTuple is a function rather than a class.

**Comment by mrolle45** [comment]
Thanks.
I'm actually moving away from NamedTuple and namedtuple classes, in favor of attrs.
My cache.py has a metaclass which transforms a class definition in the style of NamedTuple and adds more functionality (that is, caching created instances based on constructor parameters).  The result class has a NamedTuple subclass as a base class.  This obviously won't work on 3.9+, so I'll have to figure out a different way of doing this (eventually).
BTW, I managed to track down the crash and it seems to have something to do with stubs in your typeshed.

**Comment by rchen152** [comment]
This doesn't crash anymore. (Our latest release contains a significant refactor of our NamedTuple code, so that's probably what fixed it.)
