### ISSUE TITLE
Parse errors for PyQt5/6 stubs

### ISSUE THREAD

**Issue by mharbison72** [google/pytype#1315]
I'm trying to integrate the typestubs installed with `pyqt5==5.15.7` and `pyqt6==6.2.3` on PyPI, and ran into a couple of issues.  First, with the default stub (attached with a .txt extension), it complains about too many decorators:

```
$ pytype-single -o - -v 4 --parse-pyi contrib/typehints/PyQt6/PyQt6/QtCore.pyi
Traceback (most recent call last):
  File "/home/mharbison/.local/bin/pytype-single", line 8, in <module>
    sys.exit(main())
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/single.py", line 87, in main
    return _run_pytype(options)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/single.py", line 95, in _run_pytype
    unused_ast = io.parse_pyi(options)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/io.py", line 77, in wrapper
    return f(*args, **kwargs)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/io.py", line 307, in parse_pyi
    ast = loader.load_file(options.module_name, options.input)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 374, in load_file
    return self.load_module(ModuleInfo(module_name, filename), mod_ast=mod_ast)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 386, in load_module
    mod_ast = self._module_loader.load_ast(mod_info)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/imports/module_loader.py", line 112, in load_ast
    return self._load_pyi(mod_info)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/imports/module_loader.py", line 98, in _load_pyi
    mod_ast = parser.parse_string(
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/parser.py", line 795, in parse_string
    return parse_pyi(src, filename=filename, module_name=name, options=options)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/parser.py", line 810, in parse_pyi
    root = gen_pytd.visit(root)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 31, in visit
    ret = self.visit(v)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 40, in visit
    ret = self.visit(v)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 31, in visit
    ret = self.visit(v)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 40, in visit
    ret = self.visit(v)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 34, in visit
    out = self._call_visitor(node)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/visitor.py", line 38, in _call_visitor
    raise ParseError.from_exc(e).at(node, self.filename, self.src_code)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/visitor.py", line 36, in _call_visitor
    return super()._call_visitor(node)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 55, in _call_visitor
    return visitor(node)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/parser.py", line 379, in visit_FunctionDef
    return function.NameAndSig.from_function(node, False)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/function.py", line 93, in from_function
    raise ParseError(f"Too many decorators for {name}")
pytype.pyi.types.ParseError:   File: "contrib/typehints/PyQt6/PyQt6/QtCore.pyi", line 1465
    def disconnect(a0: 'QMetaObject.Connection') -> bool: ...
   ^
ParseError: Too many decorators for disconnect
```

But https://github.com/google/pytype/issues/1179 is another report about a different problem with `@overload` and `@staticmethod`, so it must work in some cases.  So I added `from typing import overload` and replaced all `@typing.overload` with `@overload` to look like that example, and got a different error:

```
$ time pytype-single -o - -v 4 --parse-pyi contrib/typehints/PyQt6/PyQt6/QtCore.pyi
Traceback (most recent call last):
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/visitor.py", line 36, in _call_visitor
    return super()._call_visitor(node)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 55, in _call_visitor
    return visitor(node)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/parser.py", line 538, in visit_ClassDef
    return self.defs.build_class(
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/definitions.py", line 703, in build_class
    methods = function.merge_method_signatures(methods)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pytd/codegen/function.py", line 262, in merge_method_signatures
    functions[fn.name].add_overload(fn)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pytd/codegen/function.py", line 243, in add_overload
    raise OverloadedDecoratorError(self.name, None)
pytype.pytd.codegen.function.OverloadedDecoratorError: Overloaded signatures for disconnect disagree on decorators

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mharbison/.local/bin/pytype-single", line 8, in <module>
    sys.exit(main())
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/single.py", line 87, in main
    return _run_pytype(options)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/single.py", line 95, in _run_pytype
    unused_ast = io.parse_pyi(options)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/io.py", line 77, in wrapper
    return f(*args, **kwargs)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/io.py", line 307, in parse_pyi
    ast = loader.load_file(options.module_name, options.input)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 374, in load_file
    return self.load_module(ModuleInfo(module_name, filename), mod_ast=mod_ast)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/load_pytd.py", line 386, in load_module
    mod_ast = self._module_loader.load_ast(mod_info)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/imports/module_loader.py", line 112, in load_ast
    return self._load_pyi(mod_info)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/imports/module_loader.py", line 98, in _load_pyi
    mod_ast = parser.parse_string(
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/parser.py", line 795, in parse_string
    return parse_pyi(src, filename=filename, module_name=name, options=options)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/parser.py", line 810, in parse_pyi
    root = gen_pytd.visit(root)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 31, in visit
    ret = self.visit(v)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 40, in visit
    ret = self.visit(v)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/ast/visitor.py", line 34, in visit
    out = self._call_visitor(node)
  File "/home/mharbison/.local/lib/python3.8/site-packages/pytype/pyi/visitor.py", line 38, in _call_visitor
    raise ParseError.from_exc(e).at(node, self.filename, self.src_code)
pytype.pyi.types.ParseError:   File: "contrib/typehints/PyQt6/PyQt6/QtCore.pyi", line 1460
ParseError: Overloaded signatures for disconnect disagree on decorators
```

I guess it's confused that one method is static and the other isn't.  This is with pytype 2022.10.26.

Any workaround?  I doubt I need both overloads, but it would be a pain to go through all of these files and prune out the overloads.

[QtCore.pyi.txt](https://github.com/google/pytype/files/9948452/QtCore.pyi.txt)

**Comment by h-joo** [comment]
Hi, thank you for your report. Google is shifting its effort to a different approach for type checking apart from pytype, and we're not planning to put in any effort in the near future in pytype, so we'll close this issue. Please see the announcement [here](https://github.com/google/pytype/blob/main/README.md).
