### ISSUE TITLE
Traceback: "ValueError: Unresolved class: 'False'"

### ISSUE THREAD

**Issue by gvanrossum** [google/pytype#14]
When running the latest pytype on this file I get a huge traceback:
```
Traceback (most recent call last):
  File "/Users/guido/v/bin/pytype", line 202, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/Users/guido/v/bin/pytype", line 196, in main
    ret = process_one_file(input_filename, output_filename, options)
  File "/Users/guido/v/bin/pytype", line 151, in process_one_file
    options=options)
  File "/Users/guido/v/bin/pytype", line 80, in generate_pytd
    maximum_depth=(1 if options.quick else None))
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/infer.py", line 576, in infer_types
    loc, defs, builtin_names = tracer.run_program(src, filename, run_builtins)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 953, in run_program
    node, f_globals, _ = self.run_bytecode(node, code, f_globals, f_locals)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 910, in run_bytecode
    node, _ = self.run_frame(frame, node)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 252, in run_frame
    state = self.run_instruction(op, state)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 207, in run_instruction
    state = bytecode_fn(state, op)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 2021, in byte_CALL_FUNCTION
    return self.call_function_from_stack(state, op.arg, [])
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 1079, in call_function_from_stack
    state, func, posargs, namedargs, starargs, starstarargs)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 1010, in call_function_with_state
    starargs, starstarargs, fallback_to_unsolvable)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 1037, in call_function
    node, funcv, posargs, namedargs or {}, starargs, starstarargs)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/abstract.py", line 1974, in call
    node_after_call, ret = self.vm.run_frame(frame, node)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 252, in run_frame
    state = self.run_instruction(op, state)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 207, in run_instruction
    state = bytecode_fn(state, op)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 1638, in byte_LOAD_ATTR
    state, val = self.load_attr(state, obj, name)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 1184, in load_attr
    node, result = self._retrieve_attr(state.node, obj, attr)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 1167, in _retrieve_attr
    node2, attr_var = val.data.get_attribute(node, attr, val)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/abstract.py", line 2190, in get_attribute
    mod = self.vm.import_module(full_name, 0)  # 0: absolute import
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/vm.py", line 1322, in import_module
    ast = self.loader.import_name(name)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/load_pytd.py", line 201, in import_name
    mod = self._load_builtin("stdlib", module_name)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/load_pytd.py", line 162, in _load_builtin
    typeshed.parse_type_definition(subdir, module_name, version))
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/pytd/typeshed.py", line 77, in parse_type_definition
    python_version=python_version).Replace(name=module)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/pytd/utils.py", line 342, in ParsePyTD
    ast = visitors.LookupClasses(ast, builtins.GetBuiltinsPyTD())
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/pytd/parse/visitors.py", line 542, in LookupClasses
    module.Visit(VerifyLookup())
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 261, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 226, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 261, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 276, in _VisitNode
    new_node = visitor.Visit(new_node, *args, **kwargs)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/pytd/parse/visitors.py", line 82, in Visit
    self, node, *args, **kwargs)
  File "/Users/guido/v/lib/python2.7/site-packages/pytype/pytd/parse/visitors.py", line 558, in VisitClassType
    raise ValueError("Unresolved class: %r" % node.name)
ValueError: Unresolved class: 'False'
```
[simple.py.txt](https://github.com/google/pytype/files/101614/simple.py.txt)

**Comment by matthiaskramm** [comment]
I can't reproduce this. Are you using a custom typeshed?

In any case, it looks like it's stumbling over a module-level or class-level constant that's declared as
  x = False
instead of
  x = ...  # type: bool
.

I'll tweak my parser to allow this, unless we decide that we want to discourage this kind of shortcut.

(The backtrace might also be due to default parameters declared as "x:bool = False" instead of "x:bool = ...". I'm in the process of fixing those in typeshed)

**Comment by gvanrossum** [comment]
The typeshed module is exactly as determined by 'git submodule update' in
pytype.

My code uses `import time` and typeshed/stdlib/2.7/time.pyi has this line:
```
accept2dyear = False
```
But replacing that with
```
accept2dyear = ... # type: bool
```
doesn't make a difference.

There are also several occurrences of ": bool = False" in typeshed.

I hope you can make your parser more lenient -- stubs are basically allowed
to contain arbitrary Python code. The common idioms are merely recommended
by the PEP.

(If you want to make the stub syntax significantly smaller we should
probably draw up a spec and rubber-stamp it as a PEP.)

**Comment by matthiaskramm** [comment]
Yeah, it's odd this doesn't happen on my machine! But since the root cause is identified, maybe it doesn't matter.

With regards to the syntax of optional parameters, I'm mostly concerned with a consistent coding style in typeshed. (Although I have to admit that I *do* miss the orthogonality of pytypedecl's `pytd`. In comparison, `pyi` feels like the wild west)

Long term, I want to load `.pyi` in pytype the same way as `.py`: Compile to bytecode and then interpret, with some preprocessing to get the type comments in there, too.

**Comment by gvanrossum** [comment]
Have you figured this one out yet? It's blocking further investigations
here.

**Comment by matthiaskramm** [comment]
I have a fix. It's in (our internal) code review.

**Comment by matthiaskramm** [comment]
Fix pushed.

(Also, the reason I couldn't reproduce this on my machine is because I had TYPESHED_HOME in my environment. D'oh!)

**Comment by gvanrossum** [comment]
Thanks!
