### ISSUE TITLE
merge-pyi is raising libcst._nodes.base.CSTValidationError / pytype.tools.merge_pyi.merge_pyi.MergeError

### ISSUE THREAD

**Issue by AlanRosenthal** [google/pytype#1402]
Running pytype on open source repo: https://github.com/google/bumble
```
pytype --pythonpath . ./bumble/device.py
```

then running merge-pyi raises an exception

```
❯ merge-pyi -i bumble/device.py .pytype/pyi/bumble/device.pyi
Traceback (most recent call last):
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 35, in merge_sources
    merged_cst = _merge_csts(py_tree=py_cst, pyi_tree=pyi_cst)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 28, in _merge_csts
    ).transform_module(py_tree)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/codemod/_codemod.py", line 108, in transform_module
    return self.transform_module_impl(tree_with_metadata)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/codemod/visitors/_apply_type_annotations.py", line 847, in transform_module_impl
    tree_with_changes = tree_with_imports.visit(self)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/module.py", line 90, in visit
    result = super(Module, self).visit(visitor)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/module.py", line 74, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 227, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 193, in visit_body_iterable
    new_child = child.visit(visitor)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/statement.py", line 443, in _visit_and_replace_children
    body=visit_sequence(self, "body", self.body, visitor),
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 177, in visit_sequence
    return tuple(visit_iterable(parent, fieldname, children, visitor))
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 159, in visit_iterable
    new_child = child.visit(visitor)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/base.py", line 237, in visit
    leave_result = visitor.on_leave(self, with_updated_children)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/matchers/_visitors.py", line 522, in on_leave
    retval = CSTTransformer.on_leave(self, original_node, updated_node)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_visitors.py", line 71, in on_leave
    updated_node = leave_func(original_node, updated_node)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/codemod/visitors/_apply_type_annotations.py", line 1318, in leave_Assign
    return self._annotate_single_target(original_node, updated_node)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/codemod/visitors/_apply_type_annotations.py", line 1015, in _annotate_single_target
    return self._apply_annotation_to_attribute_or_global(
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/codemod/visitors/_apply_type_annotations.py", line 961, in _apply_annotation_to_attribute_or_global
    cst.Name(name),
  File "<string>", line 6, in __init__
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/base.py", line 118, in __post_init__
    self._validate()
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/libcst/_nodes/expression.py", line 357, in _validate
    raise CSTValidationError("Name is not a valid identifier.")
libcst._nodes.base.CSTValidationError: Name is not a valid identifier.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/alanrosenthal/.local/bin/merge-pyi", line 8, in <module>
    sys.exit(main())
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/main.py", line 81, in main
    changed = merge_pyi.merge_files(
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 66, in merge_files
    annotated_src = merge_sources(py=py_src, pyi=pyi_src)
  File "/usr/local/google/home/alanrosenthal/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 38, in merge_sources
    raise MergeError(str(e)) from e
pytype.tools.merge_pyi.merge_pyi.MergeError: Name is not a valid identifier.
```

**Comment by rchen152** [comment]
The fix for this has been merged in LibCST. I'll leave this bug open so I remember to update pytype's required LibCST version once a new version is released.

**Comment by rchen152** [comment]
Looks like we already bumped our required libcst version to 1.0.1 in order to pick up a different fix, so this should be fixed.
