### ISSUE TITLE
Calling len on a custom class raises FlawedQuery: Bad call (--protocols)

### ISSUE THREAD

**Issue by cebtenzzre** [google/pytype#1423]
### Description
Calling len on a simple class causes pytype to fail with an exception when using --protocols. It's only visible if you run pytype-single directly or peek in the .pyi stubs generated by pytype. It looks like this:
```
pytype.convert_structural.FlawedQuery: Bad call
builtins.len(_0: MyList) -> int: ...
against:
def builtins.len(obj: Sized) -> int: ...
File: repr.py
```

### Example Code
```python
class MyList:
    def __len__(self):
        return 0

x = len(MyList())
print(x)
```

### Expected Behavior
pytype does not crash.

### Actual Behavior
```
$ pytype-single --protocols -o- repr.py
Traceback (most recent call last):
  File "/home/cebtenzzre/.local/bin/pytype-single", line 8, in <module>
    sys.exit(main())
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/single.py", line 87, in main
    return _run_pytype(options)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/single.py", line 98, in _run_pytype
    return io.process_one_file(options)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/io.py", line 77, in wrapper
    return f(*args, **kwargs)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/io.py", line 226, in process_one_file
    ret = check_or_generate_pyi(options, loader)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/io.py", line 77, in wrapper
    return f(*args, **kwargs)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/io.py", line 169, in check_or_generate_pyi
    errorlog, result, ast = generate_pyi(
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/io.py", line 123, in generate_pyi
    ret = _call(analyze.infer_types, src, options, loader, ctx=ctx)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/io.py", line 77, in wrapper
    return f(*args, **kwargs)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/io.py", line 88, in _call
    return analyze_types(
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/analyze.py", line 139, in infer_types
    ast = convert_structural.convert_pytd(ast, builtins_pytd, protocols_pytd)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/convert_structural.py", line 281, in convert_pytd
    mapping, result = solve(ast, builtins_pytd, protocols_pytd)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/convert_structural.py", line 213, in solve
    ast, builtins_pytd, protocols_pytd).solve(), extract_local(ast)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/convert_structural.py", line 169, in solve
    self.match_call_record(
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/convert_structural.py", line 108, in match_call_record
    raise FlawedQuery("Bad call\n{}{}\nagainst:\n{}".format(
pytype.convert_structural.FlawedQuery: Bad call
builtins.len(_0: MyList) -> int: ...
against:
def builtins.len(obj: Sized) -> int: ...
File: repr.py
```

### Software Versions
Python 3.10.11
pytype 2023.05.08

**Comment by rchen152** [comment]
Looks like the abstract matcher has gotten quite out of sync with the structural matcher. I tried the obvious thing of making the structural matcher allow anything to match a protocol (since the abstract matcher should catch any type errors), but that broke a bunch of our existing protocol inference tests. I think we'd have to fully implement protocol matching in the structural matcher to fix this.
