### ISSUE TITLE
merge-pyi does not support PEP 604 union syntax

### ISSUE THREAD

**Issue by cebtenzzre** [google/pytype#1446]
### Description
[PEP 604](https://peps.python.org/pep-0604/) allows writing unions as `X | Y`. This syntax can be found in the output of mypy's stubgen.
However, merge-pyi does not support this syntax, raising an exception if it comes across it.

### Example Code
**repr.py**
````python
x = 1
````
**repr.pyi**
````python
x: int | str
````

### Steps to Reproduce
```
$ merge-pyi repr.py repr.pyi
Traceback (most recent call last):
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 35, in merge_sources
    merged_cst = _merge_csts(py_tree=py_cst, pyi_tree=pyi_cst)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 28, in _merge_csts
    ).transform_module(py_tree)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/codemod/_codemod.py", line 108, in transform_module
    return self.transform_module_impl(tree_with_metadata)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/codemod/visitors/_apply_type_annotations.py", line 836, in transform_module_impl
    module_imports = self._get_module_imports(stub, import_gatherer)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/codemod/visitors/_apply_type_annotations.py", line 881, in _get_module_imports
    cst.MetadataWrapper(stub).visit(symbol_collector)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/metadata/wrapper.py", line 204, in visit
    return self.module.visit(visitor)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/module.py", line 90, in visit
    result = super(Module, self).visit(visitor)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/module.py", line 74, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 227, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 193, in visit_body_iterable
    new_child = child.visit(visitor)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/statement.py", line 443, in _visit_and_replace_children
    body=visit_sequence(self, "body", self.body, visitor),
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 177, in visit_sequence
    return tuple(visit_iterable(parent, fieldname, children, visitor))
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 159, in visit_iterable
    new_child = child.visit(visitor)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_nodes/base.py", line 219, in visit
    should_visit_children = visitor.on_visit(self)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/matchers/_visitors.py", line 720, in on_visit
    return CSTVisitor.on_visit(self, node)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/_visitors.py", line 123, in on_visit
    retval = visit_func(node)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/codemod/visitors/_apply_type_annotations.py", line 276, in visit_AnnAssign
    self._handle_Annotation(annotation=node.annotation)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/libcst/codemod/visitors/_apply_type_annotations.py", line 342, in _handle_Annotation
    raise ValueError(f"Unexpected annotation node: {node}")
ValueError: Unexpected annotation node: BinaryOperation(
    left=Name(
        value='int',
        lpar=[],
        rpar=[],
    ),
    operator=BitOr(
        whitespace_before=SimpleWhitespace(
            value=' ',
        ),
        whitespace_after=SimpleWhitespace(
            value=' ',
        ),
    ),
    right=Name(
        value='str',
        lpar=[],
        rpar=[],
    ),
    lpar=[],
    rpar=[],
)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cebtenzzre/.local/bin/merge-pyi", line 8, in <module>
    sys.exit(main())
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/main.py", line 81, in main
    changed = merge_pyi.merge_files(
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 66, in merge_files
    annotated_src = merge_sources(py=py_src, pyi=pyi_src)
  File "/home/cebtenzzre/.local/lib/python3.10/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 38, in merge_sources
    raise MergeError(str(e)) from e
pytype.tools.merge_pyi.merge_pyi.MergeError: Unexpected annotation node: BinaryOperation(
    left=Name(
        value='int',
        lpar=[],
        rpar=[],
    ),
    operator=BitOr(
        whitespace_before=SimpleWhitespace(
            value=' ',
        ),
        whitespace_after=SimpleWhitespace(
            value=' ',
        ),
    ),
    right=Name(
        value='str',
        lpar=[],
        rpar=[],
    ),
    lpar=[],
    rpar=[],
)
```

### Software Versions
pytype 2023.06.02
mypy 1.3.0

**Comment by martindemello** [comment]
looks like we need to update our libcst dependency
