### ISSUE TITLE
mercurial.util also gives pytype a sad

### ISSUE THREAD

**Issue by durin42** [google/pytype#23]
% ~/Programming/pytype/env/bin/pytype mercurial/util.py
Traceback (most recent call last):
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 264, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 218, in main
    return _run_pytype(options)
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 258, in _run_pytype
    ret = process_one_file(input_filename, output_filename, options)
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 177, in process_one_file
    options=options)
  File "/Users/augie/Programming/pytype/env/bin/pytype", line 86, in generate_pyi
    maximum_depth=(1 if options.quick else None))
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/infer.py", line 586, in infer_types
    loc, defs, builtin_names = tracer.run_program(src, filename, run_builtins)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/vm.py", line 906, in run_program
    node, f_globals, _ = self.run_bytecode(node, code, f_globals, f_locals)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/vm.py", line 863, in run_bytecode
    node, _ = self.run_frame(frame, node)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/vm.py", line 226, in run_frame
    state = self.run_instruction(op, state)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/vm.py", line 181, in run_instruction
    state = bytecode_fn(state, op)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/vm.py", line 2054, in byte_IMPORT_NAME
    name, abstract.get_atomic_python_constant(level))
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/vm.py", line 1292, in import_module
    ast = self.loader.import_name(name)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/load_pytd.py", line 175, in import_name
    self._lookup_all_classes()
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/load_pytd.py", line 133, in _lookup_all_classes
    self._finish_ast(module.ast)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/load_pytd.py", line 119, in _finish_ast
    ast.Visit(visitors.VerifyLookup())
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 261, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 226, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 261, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 226, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 261, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 226, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 261, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 276, in _VisitNode
    new_node = visitor.Visit(new_node, *args, **kwargs)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/visitors.py", line 84, in Visit
    self, node, *args, **kwargs)
  File "/Users/augie/Programming/pytype/env/lib/python2.7/site-packages/pytype/pytd/parse/visitors.py", line 669, in VisitClassType
    raise ValueError("Unresolved class: %r" % node.name)
ValueError: Unresolved class: 'bytes'

**Comment by alvarocaceres** [comment]
re-ran "pytype ./mercurial/util.py" with mercurial-3.9-rc, didn't get an exception
