### ISSUE TITLE
pytype swallows crash and outputs to .pyi

### ISSUE THREAD

**Issue by kamahen** [google/pytype#285]
See https://github.com/google/pytype/issues/269#issuecomment-479641105

There's a crash; the output (traceback) goes to the .pyi file; exit return code is 0 and there's a final message `Success: no errors found`.

**Comment by kamahen** [comment]
Looking at the generated `pytype-single` commands, there's a `--nofail` and some of them also have `--no-report-errors`. (I didn't specify `--keep-going` in the `pytype` command).

Also, it's usually bad taste to send the traceback to the output file; it should go to `stderr`.

**Comment by wiml** [comment]
I've been encountering this as well — pytype will complete with a success message, but if you look at the `.pyi` file it contains a small amount of type info followed by a traceback.

**Comment by fish2000** [comment]
I’m also having a similar issue – Upon running pytype, I eventually get `Success: no errors found`, but every single one of the generated `pyi` files looks like this:

```python
from typing import Any
def __getattr__(name: Any) -> Any: ...
# Caught error in pytype: <method 'get' of 'dict' objects> returned a result with an error set
# OverflowError: character argument not in range(0x110000)
# 
# The above exception was the direct cause of the following exception:
# 
# Traceback (most recent call last):
#   File "/usr/local/lib/python3.7/site-packages/pytype/io.py", line 131, in check_or_generate_pyi
#     input_filename=options.input, options=options, loader=loader)
#   File "/usr/local/lib/python3.7/site-packages/pytype/io.py", line 89, in generate_pyi
#     analyze.infer_types, input_filename, options, loader)
#   File "/usr/local/lib/python3.7/site-packages/pytype/io.py", line 62, in _call
#     deep=deep)
#   File "/usr/local/lib/python3.7/site-packages/pytype/analyze.py", line 654, in infer_types
#     loc, defs = tracer.run_program(src, filename, init_maximum_depth)
#   File "/usr/local/lib/python3.7/site-packages/pytype/vm.py", line 705, in run_program
#     node, f_globals, f_locals, _ = self.run_bytecode(node, code)
#   File "/usr/local/lib/python3.7/site-packages/pytype/vm.py", line 673, in run_bytecode
#     node, return_var = self.run_frame(frame, node)
#   File "/usr/local/lib/python3.7/site-packages/pytype/vm.py", line 290, in run_frame
#     state = self.run_instruction(op, state)
#   File "/usr/local/lib/python3.7/site-packages/pytype/vm.py", line 251, in run_instruction
#     state = bytecode_fn(state, op)
#   File "/usr/local/lib/python3.7/site-packages/pytype/vm.py", line 2630, in byte_IMPORT_NAME
#     module = self.import_module(name, full_name, level)
#   File "/usr/local/lib/python3.7/site-packages/pytype/vm.py", line 1339, in import_module
#     module = self._import_module(name, level)
#   File "/usr/local/lib/python3.7/site-packages/pytype/vm.py", line 1383, in _import_module
#     ast = self.loader.import_name(name)
#   File "/usr/local/lib/python3.7/site-packages/pytype/load_pytd.py", line 426, in import_name
#     ast = self._import_name(module_name)
#   File "/usr/local/lib/python3.7/site-packages/pytype/load_pytd.py", line 502, in _import_name
#     file_ast, path = self._import_file(module_name, module_name.split("."))
#   File "/usr/local/lib/python3.7/site-packages/pytype/load_pytd.py", line 569, in _import_file
#     file_ast, full_path = self._load_pyi(path, module_name)
#   File "/usr/local/lib/python3.7/site-packages/pytype/load_pytd.py", line 596, in _load_pyi
#     ast = self.load_file(filename=full_path, module_name=module_name)
#   File "/usr/local/lib/python3.7/site-packages/pytype/load_pytd.py", line 241, in load_file
#     python_version=self.python_version)
#   File "/usr/local/lib/python3.7/site-packages/pytype/pyi/parser.py", line 1250, in parse_file
#     src, name, filename)
#   File "/usr/local/lib/python3.7/site-packages/pytype/pyi/parser.py", line 430, in parse
#     defs = parser_ext.parse(self, src)
#   File "/usr/local/lib/python3.7/site-packages/pytype/pyi/parser.py", line 762, in new_type
#     base_type = self._type_map.get(name)
# SystemError: <method 'get' of 'dict' objects> returned a result with an error set
```

… these errors, incidentally, are occurring when processing modules that don’t have a module `__getattr__(…)` function defined.

I’d be happy to provide any of the rest of the output or results, the `pytype.cfg` file in use, or anything else that might shed any light on this conundrum.

**Comment by rchen152** [comment]
Sorry for not responding to this issue for so long. The comments appear to all be reporting different instances of pytype crashes, whose only common point is that pytype is using `--nofail` to continue past the crash. It's unlikely that we'll be able to get rid of `--nofail`, so I'm going to close this issue. For anyone else who comes across this: if you see a stack trace in a pyi file, please open a new issue that includes an example of code that will cause pytype to produce the stack trace.
