### ISSUE TITLE
ImportError: No module named 'StringIO'

### ISSUE THREAD

**Issue by averrin** [google/pytype#3]
Python 3.5

Traceback (most recent call last):
  File "/usr/local/bin/pytype", line 19, in <module>
    from pytype import infer
  File "/usr/local/lib/python3.5/site-packages/pytype/infer.py", line 6, in <module>
    import StringIO
ImportError: No module named 'StringIO'

**Comment by matthiaskramm** [comment]
pytype itself runs on Python 2.7. The shebang of `scripts/pytype` (a.k.a. `/usr/local/bin/pytype`) *should* say `#!/usr/bin/python2.7`.

How did you execute the command?
