### ISSUE TITLE
pytype crashes when trying to generate stubs for `werkzeug`

### ISSUE THREAD

**Issue by rowillia** [google/pytype#37]
https://github.com/rowillia/werkzeug/blob/master/werkzeug/datastructures.py

```
$ pytype werkzeug/datastructures.py:werkzeug/datastructures.pyi
Traceback (most recent call last):
  File "/usr/local/bin/pytype", line 271, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/usr/local/bin/pytype", line 228, in main
    return _run_pytype(options)
  File "/usr/local/bin/pytype", line 264, in _run_pytype
    errors_csv_file=errors_csv_file)
  File "/usr/local/bin/pytype", line 182, in process_one_file
    options=options)
  File "/usr/local/bin/pytype", line 89, in generate_pyi
    cache_unknowns=options.cache_unknowns)
  File "/usr/local/lib/python2.7/site-packages/pytype/infer.py", line 637, in infer_types
    tracer.exitpoint = tracer.analyze(loc, defs, builtin_names, maximum_depth)
  File "/usr/local/lib/python2.7/site-packages/pytype/infer.py", line 183, in analyze
    self.analyze_toplevel(node, defs, ignore)
  File "/usr/local/lib/python2.7/site-packages/pytype/infer.py", line 173, in analyze_toplevel
    node2 = self.analyze_class(value, node)
  File "/usr/local/lib/python2.7/site-packages/pytype/infer.py", line 152, in analyze_class
    node2 = self.analyze_method_var(name, b, node)
  File "/usr/local/lib/python2.7/site-packages/pytype/infer.py", line 119, in analyze_method_var
    node2 = self.analyze_method(val, node)
  File "/usr/local/lib/python2.7/site-packages/pytype/infer.py", line 111, in analyze_method
    node, fvar, args, kws, starargs, starstarargs)
  File "/usr/local/lib/python2.7/site-packages/pytype/infer.py", line 93, in call_function_in_frame
    state, var, args, kwargs, starargs, starstarargs)
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 630, in call_function_with_state
    starargs, starstarargs, fallback_to_unsolvable)
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 657, in call_function
    node, funcv, posargs, namedargs or {}, starargs, starstarargs)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 2717, in call
    namedargs, starargs, starstarargs)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 2558, in call
    node_after_call, ret = self.vm.run_frame(frame, node)
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 186, in run_frame
    state = self.run_instruction(op, state)
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 141, in run_instruction
    state = bytecode_fn(state, op)
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 1721, in byte_CALL_FUNCTION
    return self.call_function_from_stack(state, op.arg, [])
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 707, in call_function_from_stack
    state, func, posargs, namedargs, starargs, starstarargs)
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 630, in call_function_with_state
    starargs, starstarargs, fallback_to_unsolvable)
  File "/usr/local/lib/python2.7/site-packages/pytype/vm.py", line 657, in call_function
    node, funcv, posargs, namedargs or {}, starargs, starstarargs)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 1632, in call
    starargs, starstarargs)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 1690, in _call_with_view
    starargs, starstarargs, record_call=True)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 1749, in find_matching_signature
    starargs, starstarargs, record_call)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 1397, in call_with_view
    r = self._call_with_values(node, arg_dict, view)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 1433, in _call_with_values
    subst = self._compute_subst(node, arg_dict, view)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 1465, in _compute_subst
    subst = _match_value_against_type(actual, formal, subst, node, view)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 137, in _match_value_against_type
    return left.match_against_type(other_type, subst, node, view)
  File "/usr/local/lib/python2.7/site-packages/pytype/abstract.py", line 471, in match_against_type
    raise NotImplementedError("Matching not implemented for %s", type(self))
NotImplementedError: ('Matching not implemented for %s', <class 'pytype.abstract.SuperInstance'>)
```

**Comment by matthiaskramm** [comment]
Interesting. We'll take a look.
