### ISSUE TITLE
pytype setup omits pytype.tools.traces

### ISSUE THREAD

**Issue by kamahen** [google/pytype#372]
This is with the latest pull from github (2019.7.30). I fixed it by:
```
cp -pir ./pytype/tools/traces/ ~/.local/lib/python3.6/site-packages/pytype/tools/
```

Here's the error I got:
```
Traceback (most recent call last):
  File "/home/peter/.local/bin/pyxref", line 11, in <module>
    load_entry_point('pytype==2019.7.30', 'console_scripts', 'pyxref')()
  File "/home/peter/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/peter/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/peter/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/peter/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/tools/xref/main.py", line 15, in <module>
    from pytype.tools.xref import indexer
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/tools/xref/indexer.py", line 18, in <module>
    from pytype.tools.traces import source
ModuleNotFoundError: No module named 'pytype.tools.traces'
```

**Comment by kamahen** [comment]
I used these commands to install (I had previously deleted all pytype files from ~/.local):
```
cd ~/src/pytype
git pull --recurse-submodules
git submodule init
git submodule update
python3 -m pip install --upgrade --user .
```

**Comment by rchen152** [comment]
Thanks for catching this; I opened a PR to fix it.

**Comment by kamahen** [comment]
Verified fixed.
