### ISSUE TITLE
Cannot build on macos

### ISSUE THREAD

**Issue by shacklestone** [google/pytype#405]
Hello,

I've gone through the CONTRIBUTING guidelines and run these two commands:
`python build_scripts/build.py --debug`
`./out/bin/pytype-single --help`

And I get this output:

```
Traceback (most recent call last):
  File "./bin/pytype", line 13, in <module>
    from pytype.tools.analyze_project import main
  File "/Users/davidbarker/code/pytype/out/pytype/tools/analyze_project/main.py", line 30, in <module>
    from pytype import io
  File "/Users/davidbarker/code/pytype/out/pytype/io.py", line 13, in <module>
    from pytype import analyze
  File "/Users/davidbarker/code/pytype/out/pytype/analyze.py", line 13, in <module>
    from pytype import output
  File "/Users/davidbarker/code/pytype/out/pytype/output.py", line 11, in <module>
    from pytype import typing_overlay
  File "/Users/davidbarker/code/pytype/out/pytype/typing_overlay.py", line 8, in <module>
    from pytype import collections_overlay
  File "/Users/davidbarker/code/pytype/out/pytype/collections_overlay.py", line 12, in <module>
    from pytype.pyi import parser
  File "/Users/davidbarker/code/pytype/out/pytype/pyi/parser.py", line 9, in <module>
    from pytype.pyi import parser_ext  # pytype: disable=import-error
ImportError: cannot import name parser_ext
```

**Comment by rchen152** [comment]
@martindemello Do you have any idea why this would be broken on macos?

**Comment by martindemello** [comment]
no idea either :( can you check out/ninja.log and see if it builds parser_ext.so successfully? e.g. i have
````
out/ninja.log
54:[54/293] Building CXX object pytype/pyi/CMakeFiles/pytype.pyi.parser_ext.dir/parser_ext.cc.o
57:[57/293] Building CXX object pytype/pyi/CMakeFiles/pytype.pyi.parser_ext.dir/lexer.lex.cc.o
58:[58/293] Building CXX object pytype/pyi/CMakeFiles/pytype.pyi.parser_ext.dir/parser.tab.cc.o
60:[60/293] Linking CXX shared library pytype/pyi/parser_ext.so
````

**Comment by shacklestone** [comment]
Yes, that succeeds.

```
7 warnings generated.
[7/293] Linking CXX shared library pytype/pyi/parser_ext.dylib
[8/293] Building CXX object pytype/typegraph/CMakeFiles/pytype.typegraph.reachable.dir/reachable.cc.o
[9/293] Linking CXX static library pytype/typegraph/libreachable.a
[10/293] Building CXX object pytype/typegraph/CMakeFiles/pytype.typegraph.typegraph.dir/typegraph.cc.o
```

Listing that output directory:
```
$ ls ./out/pytype/pyi
CMakeFiles		location.hh		parser_ext.dylib
__init__.py		parse_typeshed_test.py	parser_memleak_test.py
cmake_install.cmake	parser.py		parser_test.py
lexer.lex.cc		parser.tab.cc		position.hh
lexer_test.py		parser.tab.hh		stack.hh
```

**Comment by shacklestone** [comment]
Same in python 2 or 3:

```
$ python3.7 ./out/bin/pytype-single 
Traceback (most recent call last):
  File "./out/bin/pytype-single", line 13, in <module>
    from pytype import main
  File "/Users/davidbarker/code/pytype/out/pytype/main.py", line 17, in <module>
    from pytype import config
  File "/Users/davidbarker/code/pytype/out/pytype/config.py", line 14, in <module>
    from pytype import load_pytd
  File "/Users/davidbarker/code/pytype/out/pytype/load_pytd.py", line 10, in <module>
    from pytype.pyi import parser
  File "/Users/davidbarker/code/pytype/out/pytype/pyi/parser.py", line 9, in <module>
    from pytype.pyi import parser_ext  # pytype: disable=import-error
ImportError: cannot import name 'parser_ext' from 'pytype.pyi' (/Users/davidbarker/code/pytype/out/pytype/pyi/__init__.py)
$ cat !$
cat out/pytype/pyi/__init__.py

$
```

**Comment by yilei** [comment]
What happens if you just rename `parser_ext.dylib` to `parser_ext.so`?

**Comment by gpshead** [comment]
While renaming the .dylib files to .so does "work" it's a bug in pytype's cmake based build system that it produces .dylib files in the first place for these.  It appears that is likely due to how https://github.com/google/pytype/blob/master/cmake/modules/PyTypeUtils.cmake#L360 defined `py_extension`.

**Comment by rchen152** [comment]
pytype has switched to using pybind11 instead of a custom py_extension, so this error shouldn't occur anymore (although there might be other issues with running the tests on macos).
