### ISSUE TITLE
"else" causes error

### ISSUE THREAD

**Issue by mfojtak** [google/pytype#419]
I am trying to parse simple if-else using following code:
```python
from typed_ast import ast3
from pytype.tools.annotate_ast import annotate_ast
from pytype import config

source = """
def f(arg: int):
    if True:
        a = 0
    else:
        a = 1
    return arg
"""
options = config.Options.create(python_version=(3,7))
ast_factory = lambda unused_options: ast3
module = annotate_ast.annotate_source(source, ast_factory, options)
```

It throws error:
```
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    module = annotate_ast.annotate_source(source, ast_factory, options)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/annotate_ast/annotate_ast.py", line 31, in annotate_source
    visitor.visit(module)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 25, in visit
    ret = self.visit(v)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 34, in visit
    self.visit(v)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 25, in visit
    ret = self.visit(v)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 34, in visit
    self.visit(v)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 25, in visit
    ret = self.visit(v)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 34, in visit
    self.visit(v)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 25, in visit
    ret = self.visit(v)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 34, in visit
    self.visit(v)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 28, in visit
    out = self._call_visitor(node)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/traces/visitor.py", line 53, in _call_visitor
    return visitor(node)
  File "/opt/conda/lib/python3.7/site-packages/pytype/tools/annotate_ast/annotate_ast.py", line 63, in visit_Name
    unused_loc, entry = next(iter(ops), None)
TypeError: cannot unpack non-iterable NoneType object
```
The code is parsed fine without the "else" branch.
What is wrong?

**Comment by rchen152** [comment]
`annotate_ast` is still a work-in-progress. We should add a README clarifying this.

**Comment by rchen152** [comment]
FYI the crash will be fixed when https://github.com/google/pytype/commit/059d213832e60f6db6faf4cad76e7724f3b6b653 is released, but the code still won't be parsed correctly (the type is set to `None`).
