### ISSUE TITLE
When using ctypes, an Array field in a Structure causes an error.

### ISSUE THREAD

**Issue by relent95** [google/pytype#448]
When this .py file is processed,
```
import ctypes

class X(ctypes.Structure):
	_fields_ = [('a', ctypes.c_ushort * 2)]
```
This .pyi file is created.
```

from typing import Any
def __getattr__(name: Any) -> Any: ...
# Caught error in pytype: Unbound type parameter _CT in X._fields_
# Traceback (most recent call last):
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/io.py", line 156, in check_or_generate_pyi
#     input_filename=options.input, options=options, loader=loader)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/io.py", line 113, in generate_pyi
#     analyze.infer_types, input_filename, options, loader)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/io.py", line 65, in wrapper
#     return f(*args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/io.py", line 84, in _call
#     deep=deep)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/analyze.py", line 651, in infer_types
#     ast = tracer.compute_types(defs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/analyze.py", line 567, in compute_types
#     return ty.Visit(visitors.AdjustTypeParameters())
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 214, in Visit
#     return _Visit(self, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 242, in _Visit
#     return _VisitNode(node, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 326, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 293, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 326, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 293, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 326, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 326, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 293, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 326, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 293, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 326, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 293, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 326, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 293, in _VisitNode
#     new_child = _VisitNode(child, visitor, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/parse/node.py", line 344, in _VisitNode
#     new_node = visitor.Visit(new_node, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/pytd_visitors.py", line 184, in Visit
#     self, node, *args, **kwargs)
#   File "/d/test_pytype/python3/lib/python3.7/site-packages/pytype-2019.10.17-py3.7-linux-x86_64.egg/pytype/pytd/visitors.py", line 1379, in VisitTypeParameter
#     node.name, self._GetFullName(self.constant_name)))
# pytype.pytd.visitors.ContainerError: Unbound type parameter _CT in X._fields_
```

**Comment by rchen152** [comment]
Thanks for the report! We've gotten a couple internal bugs about ctypes as well, and as best I can tell, the issue is with the ctypes._CData class that a lot of the ctypes classes inherit from. It does some unusual things with metaclasses and typevars that confuse pytype.

**Comment by rchen152** [comment]
pytype now generates the following pyi for the code in this issue:
```
# (generated with --quick)                                                                                                                          

from typing import List, Tuple, Type, TypeVar

ctypes: module

_CT = TypeVar('_CT', bound=ctypes._CData)

class X(ctypes.Structure):
    _fields_: List[Tuple[str, Type[ctypes.Array[_CT]]]]
```
So I believe this is fixed.
