### ISSUE TITLE
pyxref crash (KeyError with a dataclass field)

### ISSUE THREAD

**Issue by kamahen** [google/pytype#470]
Presumably this is caused by a line in the code that's being analyzed that has `self.as_name`; but it's non-trivial to give you a short reproduction. If you can't figure out the issue from the information below, I'll see what I can do to reproduce this for you.

It appears that pyxref is confused about what variable is being referenced -- I *think* the code that caused the error is (`.as_name` doesn't appear anywhere else in my code):
```
    def add_fqns(self, ctx: FqnCtx) -> Base:
        dotted_name = xcast(DottedNameNode, self.dotted_name.add_fqns(ctx))
        if self.as_name:
            top_name = self.as_name.add_fqns(ctx)
            ...
```
(where `xcast` is similar to `typing.cast`).
It appears that `self` is mistakenly tagged as type `DottedNameNode` (a dataclass with field `items`) instead of `ImportDottedAsNameNode` (a dataclass with fields `dotted_name`, `as_name`).

I trapped the error in pytype/output.py at line 470 by adding this:
`print(f"get_parameter: p={p!r} kwonly={kwonly!r} exc={exc!r} sig.annotations={sig.annotations!r}")`
and got
`get_parameter: p='as_name' kwonly=False exc=KeyError('as_name',) sig.annotations={'dotted_name': InterpreterClass(DottedNameNode), 'self': unsolveable}`

Here's the traceback (invoked with `pyxref --debug --protocols --python_version=3.7`):
```
Pytype error: KeyError: as_name
Traceback (most recent call last):
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/io.py", line 321, in wrap_pytype_exceptions
    yield
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/tools/xref/indexer.py", line 1220, in process_file
    tracer_vm=vm)
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/analyze.py", line 654, in infer_types
    ast = tracer.compute_types(defs)
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/analyze.py", line 563, in compute_types
    self.pytd_for_types(defs),
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/analyze.py", line 470, in pytd_for_types
    d = option.to_pytd_def(self.exitpoint, name)  # Deep definition
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/abstract.py", line 247, in to_pytd_def
    return self.vm.convert.pytd_convert.value_to_pytd_def(node, self, name)
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/output.py", line 345, in value_to_pytd_def
    return self._class_to_def(node, v, name)
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/output.py", line 588, in _class_to_def
    methods[name] = self.value_to_pytd_def(node, value, name).Visit(
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/output.py", line 332, in value_to_pytd_def
    return self._simple_func_to_def(node, v, name)
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/output.py", line 472, in _simple_func_to_def
    params = [get_parameter(p, False) for p in sig.param_names]
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/output.py", line 472, in <listcomp>
    params = [get_parameter(p, False) for p in sig.param_names]
  File "/home/peter/.local/lib/python3.6/site-packages/pytype/output.py", line 470, in get_parameter
    return pytd.Parameter(p, sig.annotations[p].get_instance_type(node),
KeyError: 'as_name'
```

**Comment by rchen152** [comment]
Could you please provide a way to reproduce the crash? It doesn't have to be "short" - I'm happy to spend some time minimizing it - but there's too much missing context in the code snippet above.

**Comment by kamahen** [comment]
This file reproduces the problem.

[repro_470.py.txt](https://github.com/google/pytype/files/3946892/repro_470.py.txt)

**Comment by rchen152** [comment]
Thanks! I'll take a look.

**Comment by martindemello** [comment]
had to add a few missing classes to get it to build with pytype at all, file attached
[t.py.txt](https://github.com/google/pytype/files/3947296/t.py.txt)

**Comment by kamahen** [comment]
Sorry - I didn't think to run it through pytype, just pyxref.

If you think you have a fix, maybe send the patch to me first because the actual code is more complex (different base classes, different way of doing the cast, etc.)

**Comment by martindemello** [comment]
could not reproduce, either running 3.6 or 3.7 (i did not try running with host 3.6 and target 3.7)

**Comment by martindemello** [comment]
we just pushed a bunch of dataclass fixes that might have covered the issue, could you sync to head and try again?

**Comment by kamahen** [comment]
I'm getting a different crash, which I'll need to look into.
Also, the new dataclass code seems to have found some subtle bugs in my code -- good job!

**Comment by kamahen** [comment]
The new crash seems to be an unrelated issue and it's not a crash after all, just pyxref's way of complaining that an imported file had a type error.
