### ISSUE TITLE
merge-pyi doesn't work with pyi file with backticks generated by pytype

### ISSUE THREAD

**Issue by azdkj532** [google/pytype#481]
This is input:
```python
# test.py
from collections import namedtuple
Hello = namedtuple('Hello', ['a', 'b', 'c'])
```
This is what I got :
```python
# .pytype/pyi/test.pyi
# (generated with --quick)

import collections
from typing import Any, Callable, Iterable, Sized, Tuple, Type, TypeVar, Union

Hello = `namedtuple-Hello-a-b-c`

_Tnamedtuple-Hello-a-b-c = TypeVar('_Tnamedtuple-Hello-a-b-c', bound=`namedtuple-Hello-a-b-c`)

class `namedtuple-Hello-a-b-c`(tuple):
    __slots__ = ["a", "b", "c"]
    __dict__: collections.OrderedDict[str, Any]
    _fields: Tuple[str, str, str]
    a: Any
    b: Any
    c: Any
    def __getnewargs__(self) -> Tuple[Any, Any, Any]: ...
    def __getstate__(self) -> None: ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __new__(cls: Type[`_Tnamedtuple-Hello-a-b-c`], a, b, c) -> `_Tnamedtuple-Hello-a-b-c`: ...
    def _asdict(self) -> collections.OrderedDict[str, Any]: ...
    @classmethod
    def _make(cls: Type[`_Tnamedtuple-Hello-a-b-c`], iterable: Iterable, new = ..., len: Callable[[Sized], int] = ...) -> `_Tnamedtuple-Hello-a-b-c`: ...
    def _replace(self: `_Tnamedtuple-Hello-a-b-c`, **kwds) -> `_Tnamedtuple-Hello-a-b-c`: ...

def namedtuple(typename: str, field_names: Union[str, Iterable[str]], *, verbose: bool = ..., rename: bool = ...) -> type: ...
```
Backticks cause problem when I try using `merge-pyi`.
```
Traceback (most recent call last):
  File "/home/larry/.pyenv/versions/3.7.5/bin/merge-pyi", line 11, in <module>
    load_entry_point('pytype==2019.12.6', 'console_scripts', 'merge-pyi')()
  File "/home/larry/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pytype/tools/merge_pyi/main.py", line 100, in main
    annotated_src = merge_pyi.annotate_string(args, py_src, pyi_src)
  File "/home/larry/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 969, in annotate_string
    parsed_pyi = Pyi.parse(pyi_src)
  File "/home/larry/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 780, in parse
    tree = Util.parse_string(text)
  File "/home/larry/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pytype/tools/merge_pyi/merge_pyi.py", line 166, in parse_string
    return cls.driver.parse_string(text)
  File "/home/larry/.pyenv/versions/3.7.5/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/larry/.pyenv/versions/3.7.5/lib/python3.7/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/larry/.pyenv/versions/3.7.5/lib/python3.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=25, value='`', context=(' ', (10, 6))
```

**Comment by rchen152** [comment]
Oof, that's embarrassing. I'll look into this more when I have the time.

**Comment by azdkj532** [comment]
Is there any guide or document for the codebase ? Maybe I can file a PR.

**Comment by rchen152** [comment]
Unfortunately, we don't have any developer docs yet - one of our goals for this quarter is to create some. merge-pyi is pretty self-contained: it's a main.py plus https://github.com/google/pytype/blob/master/pytype/tools/merge_pyi/merge_pyi.py.

**Comment by rchen152** [comment]
Sorry for the late follow-up. merge_pyi assumes that pyi files can be parsed as Python code:
https://github.com/google/pytype/blob/4772ad6fe89f4df75ae3d08e7374f68074175d4a/pytype/tools/merge_pyi/merge_pyi.py#L166
For namedtuples, pytype intentionally generates names that aren't legal Python identifiers to avoid name clashes. Perhaps we should instead require that the name of the namedtuple match the variable that it is assigned to (like we do for TypeVars) so that we can use that as the class name.

**Comment by rchen152** [comment]
The pyi parser no longer generates backticks, so this should be fixed.
