### ISSUE TITLE
When the try statement includes return statement, all errors in the except statement are ignored.

### ISSUE THREAD

**Issue by Gapex** [google/pytype#482]
```shell
Python 3.6.4 :: Anaconda, Inc.

Name: pytype
Version: 2019.10.17
Summary: Python type inferencer
Home-page: https://google.github.io/pytype
Author: None
Author-email: None
License: UNKNOWN
Location: /home/gaoyunpeng/miniconda3/envs/restore/lib/python3.6/site-packages
Requires: six, ninja, pyyaml, typed-ast, importlab, attrs
Required-by:
```

```python
def func_needs_arg(arg: int):
    pass

class ClassNeedsArg:
    def __init__(self, arg: int) -> None:
        pass

def construct_result(arg: int):
    if arg < 0:
        raise Exception()
    return arg

def wrapper(arg: int) -> int:
    try:
        return construct_result(arg)
    except Exception as e:
        # some errorneous statements
        c = 1 + '2'
        func_needs_arg()
        ClassNeedsArg()

wrapper(-1)
```

pytype result:
```shell
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/home/gaoyunpeng/workspace/python/test_pytype/.pytype'
ninja: no work to do.
Success: no errors found
```

result of execution:
```python
Traceback (most recent call last):
  File "test.py", line 15, in wrapper
    return construct_result(arg)
  File "test.py", line 10, in construct_result
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 22, in <module>
    wrapper(-1)
  File "test.py", line 18, in wrapper
    c = 1 + '2'
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

the follwing statements are obviously invalid:
```python
c = 1 + '2'
func_needs_arg()
ClassNeedsArg()
```

**Comment by rchen152** [comment]
This works now! (as in, pytype finds the errors in all three lines in the `except`) @martindemello made some improvements to try/except handling in pytype-2021.07.19, so that's probably what fixed this bug.
