### ISSUE TITLE
Current master fails to pip install

### ISSUE THREAD

**Issue by vlasovskikh** [google/pytype#51]
```
$ pip install -U git+git://github.com/google/pytype
Collecting git+git://github.com/google/pytype
  Cloning git://github.com/google/pytype to /tmp/pip-SFKRsw-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-SFKRsw-build/setup.py", line 22, in <module>
        assert 'typeshed/stdlib/2.7/*.pyi' in typeshed
    AssertionError
```

**Comment by vlasovskikh** [comment]
It affects the automated checks of PRs in the Typeshed repo.

**Comment by matthiaskramm** [comment]
It seems https://github.com/google/pytype/pull/46 is getting rolled back every time we export. Looking into it.

In any case, I just did a manual fix, so typeshed tests should work again.

**Comment by vlasovskikh** [comment]
Thank you!

**Comment by arita37** [comment]
Any fixing steps ?

**Comment by matthiaskramm** [comment]
arita37: Just doing "git pull" in pytype should give you the fixed version.
