### ISSUE TITLE
self-check: Graph contains a cycle or graph changed during iteration

### ISSUE THREAD

**Issue by sheerluck** [google/pytype#547]
`networkx.__version__`  == '2.4'
```
$ pytype /usr/lib/python3.8/site-packages/pytype
Computing dependencies
/usr/lib/python3.8/site-packages/IPython/kernel/__init__.py:12: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  warn("The `IPython.kernel` package has been deprecated since IPython 4.0."
/usr/lib/python3.8/site-packages/IPython/frontend.py:20: ShimWarning: The top-level `frontend` package has been deprecated since IPython 1.0. All its subpackages have been moved to the top `IPython` level.
  warn("The top-level `frontend` package has been deprecated since IPython 1.0. "
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/pytype", line 11, in <module>
    load_entry_point('pytype==2020.4.1', 'console_scripts', 'pytype')()
  File "/usr/lib/python3.8/site-packages/pytype/tools/analyze_project/main.py", line 93, in main
    importlab.output.formatted_deps_list(import_graph))
  File "/usr/lib/python3.8/site-packages/importlab/output.py", line 71, in formatted_deps_list
    for node, deps in import_graph.deps_list():
  File "/usr/lib/python3.8/site-packages/importlab/graph.py", line 189, in deps_list
    for node in nx.topological_sort(self.graph):
  File "/usr/lib/python3.8/site-packages/networkx/algorithms/dag.py", line 210, in topological_sort
    raise nx.NetworkXUnfeasible("Graph contains a cycle or graph changed "
networkx.exception.NetworkXUnfeasible: Graph contains a cycle or graph changed during iteration
```

**Comment by rchen152** [comment]
To run pytype on pytype, you should do so on the GitHub source code. So something like:
```
pip install pytype
git clone git@github.com:google/pytype.git
cd pytype
pytype
```
