### ISSUE TITLE
Failure while running tests.

### ISSUE THREAD

**Issue by souravbadami** [google/pytype#557]
Test Stacktrace:

```
Running tests in module pytype.abstract_test ...
Traceback (most recent call last):
  File "/Users/dummy/google/pytype/build_scripts/test_module.py", line 187, in run_tests_in_module
    mod_object = __import__(options.fq_mod_name, fromlist=[fq_pkg_name])
  File "/Users/dummy/google/pytype/out/pytype/abstract_test.py", line 5, in <module>
    from pytype import config
  File "/Users/dummy/google/pytype/out/pytype/config.py", line 15, in <module>
    from pytype import load_pytd
  File "/Users/dummy/google/pytype/out/pytype/load_pytd.py", line 10, in <module>
    from pytype.pyi import parser
  File "/Users/dummy/google/pytype/out/pytype/pyi/parser.py", line 9, in <module>
    from pytype.pyi import parser_ext  # pytype: disable=import-error
ImportError: cannot import name 'parser_ext' from 'pytype.pyi' (/Users/dummy/google/pytype/out/pytype/pyi/__init__.py)
```

Build Log:

```
Previous build config was different; cleaning 'out' directory.

Running CMake ...

-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found BISON: /usr/local/opt/bison/bin/bison (found suitable version "3.5.4", minimum required is "3.0.2")
-- Found FLEX: /usr/bin/flex (found suitable version "2.5.35", minimum required is "2.5.35")
-- Found PythonInterp: /Users/dummy/google/pytype/venv3/bin/python3.7 (found version "3.7.6")
-- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib (found version "3.7.6")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   pytype.pyi.parser_ext
   pytype.typegraph.cfg

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/dummy/google/pytype/out

Building all targets with Ninja ...

Pytype built successfully!
```

**OS**: macOS Mojave (10.14.6)

**Comment by rchen152** [comment]
What command did you use to run the tests? Based on the build warning, we probably need to set `MACOSX_RPATH` to ...something for our tests to run on macOS.

Luckly, merge-pyi is self-contained, so you should be able to test it with `python -m unittest pytype.tools.merge_pyi.merge_pyi_test`, bypassing the broken build.

**Comment by souravbadami** [comment]
I used: `python3 build_scripts/run_tests.py`.
Got it running using `python -m unittest pytype.tools.merge_pyi.merge_pyi_test` as you mentioned.

Another workaround for this is to replace `parser_ext.dylib` with `parser_ext.so` (Discussion: https://github.com/google/pytype/issues/405#issuecomment-534305258).
I'll look into it and will see what can be done.

**Comment by rchen152** [comment]
Oh right, I forgot about #405 - thanks for finding that. I'll close this issue; let's move conversation over to that one in order to keep things in one place.
