### ISSUE TITLE
Parser crash on a generic type alias

### ISSUE THREAD

**Issue by JelleZijlstra** [google/pytype#59]
My typeshed branch https://github.com/JelleZijlstra/typeshed/tree/fileinput crashes pytype with 

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/pytd", line 88, in <module>
    main()
  File "/home/travis/virtualenv/python2.7.9/bin/pytd", line 64, in main
    parsed = parser.parse_string(sourcecode, filename=filename_in)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytype/pyi/parser.py", line 833, in parse_string
    src, name, filename)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytype/pyi/parser.py", line 293, in parse
    defs = parser_ext.parse(self, src)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytype/pyi/parser.py", line 556, in new_type
    return self._parameterized_type(base_type, parameters)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytype/pyi/parser.py", line 631, in _parameterized_type
    return pytd.GenericType(base_type=base_type, parameters=parameters)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytype/pytd/parse/node.py", line 107, in __init__
    self._CHECKER.check(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytype/pytd/parse/preconditions.py", line 139, in check
    self._check_arg(condition, name, value)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytype/pytd/parse/preconditions.py", line 146, in _check_arg
    raise PreconditionError("argument=%s: %s." % (name, e.message))
pytype.pytd.parse.preconditions.PreconditionError: argument=base_type: (actual=CallableType, expected=NamedType) or (actual=CallableType, expected=ClassType).
```

**Comment by matthiaskramm** [comment]
Thanks for the report. Looks like it's due to (simplified): 

```
_Opener = Callable[[_Path, str], IO[AnyStr]]
openhook = _Opener[AnyStr]
```

I'm having difficulty parsing this, too. What does it mean?

**Comment by JelleZijlstra** [comment]
It's a type alias that is generic over AnyStr, plus an application of the generic that applies AnyStr to it. It's used on a function that takes an `_Opener[AnyStr]` and returns an `Iterable[AnyStr]`.

**Comment by matthiaskramm** [comment]
I see. This is the first time I've seen a generic type alias! pytype doesn't support this yet, even if we were to fix the crash.

Can you use the long version, `Callable[[_Path, str], IO[AnyStr]]`, in the definition of `def input`, as a workaround?

**Comment by JelleZijlstra** [comment]
Sure, thanks for diagnosing this!

**Comment by rchen152** [comment]
I can't reproduce this anymore. I tried running `pytype --parse-pyi` on:
```
import os
import sys
from typing import Any, AnyStr, Callable, IO, Iterable, Text, Union
if sys.version_info >= (3, 6):
  _Path = Union[Text, bytes, os.PathLike[Any]]
else:
  _Path = Union[Text, bytes]
_Opener = Callable[[_Path, str], IO[AnyStr]]
openhook = _Opener[AnyStr]
```
and it doesn't complain.
