### ISSUE TITLE
crash with two files importing each other: AttributeError: 'UnionType' object has no attribute 'cls'

### ISSUE THREAD

**Issue by Akuli** [google/pytype#626]
I have a "minimal" repro and unfortunately it doesn't seem to get much more minimal than this (still two files)

`file1.pyi`:

```
from typing import List, Tuple, Union
import file2
T = TypeVar("T")
FooSequence = Union[List[T], Tuple[T, ...]]
def foo(font: file2.Strings) -> None: ...
```

`file2.pyi`:

```
import file1
Strings = file1.FooSequence[str]
```

pytype 2020.07.20 says:

```
Traceback (most recent call last):
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/io.py", line 65, in wrapper
    return f(*args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/io.py", line 292, in parse_pyi
    ast = loader.finish_and_verify_ast(ast)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/load_pytd.py", line 436, in finish_and_verify_ast
    self._verify_pyi(ast)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/load_pytd.py", line 363, in _verify_pyi
    pyval.Visit(visitors.VerifyContainers())
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 213, in Visit
    return _Visit(self, visitor, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 241, in _Visit
    return _VisitNode(node, visitor, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 325, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 292, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 325, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 292, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 325, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 292, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 325, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/parse/node.py", line 314, in _VisitNode
    status = visitor.Enter(node, *args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/pytd_visitors.py", line 179, in Enter
    return self.enter_functions[node.__class__.__name__](
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pytd/visitors.py", line 1409, in EnterGenericType
    if not pytd.IsContainer(base_type.cls):
AttributeError: 'UnionType' object has no attribute 'cls'
```

**Comment by rchen152** [comment]
Thanks, I was able to reproduce the crash. (By the way, I assume 'wat' in file2 is supposed to be 'file1'.)

**Comment by rchen152** [comment]
Ok, when something like a union is parameterized in the same file in which it's defined, we use the fact that it's not a simple name to detect that it needs special processing: https://github.com/google/pytype/blob/b1f27ecaa005e2d15f4dec20dd2b5b2d74087218/pytype/pyi/parser.py#L767. But when the alias is imported, it does look like a simple name, so we create a normal parameterized type, but then a union is later substituted in, creating a malformed type. I think when the union is substituted in, we need to check again whether the macro processing is needed.

I'll keep poking at this on Monday.

**Comment by rchen152** [comment]
This issue is now fixed at head; assuming the nightly build looks good, I should be able to cut a new release tomorrow.

**Comment by rchen152** [comment]
Today's release can successfully parse both files in the first comment.
