### ISSUE TITLE
imports_map_loader_test relies on $TMPDIR = "/tmp"

### ISSUE THREAD

**Issue by delroth** [google/pytype#629]
Trying to run `imports_map_loader_test` on a system with `TMPDIR=/run/user/1000` results in the test failing with the following error:

```
FAIL: pytype.imports_map_loader_test.ImportMapLoaderTest.test_imports_info_filter
Traceback (most recent call last):
  File "/tmp/testpytype/source/out/pytype/imports_map_loader_test.py", line 74, in test_imports_info_filter
    ("%s/a/__init__" % d.path[1:], os.devnull),
  File "/nix/store/m2yz7829mzprnwmv7j3s9kwlwcv7yqil-python3.7-six-1.15.0/lib/python3.7/site-packages/six.py", line 679, in assertCountEqual
    return getattr(self, _assertCountEqual)(*args, **kwargs)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  ('run/__init__', '/dev/null')
First has 1, Second has 0:  ('run/user/__init__', '/dev/null')
First has 1, Second has 0:  ('run/user/1000/__init__', '/dev/null')
First has 0, Second has 1:  ('tmp/__init__', '/dev/null')
```

**Comment by rchen152** [comment]
Thanks for the report; I have a fix for this in the pipeline.
