### ISSUE TITLE
AttributeError on bare raise? (Python3 code being analyzed)

### ISSUE THREAD

**Issue by byllyfish** [google/pytype#63]
I'm seeing an error analyzing Python3.5/Python3.6 code containing a bare "raise" line.

pytype (Latest commit 4378e98f from git, dated August 8), Python 2.7.10 on Mac OS X

This is a simplification of the code that is failing. Am I doing something wrong? There is no failure if I remove the "-V 3.5" argument.

```bash
$ cat bare_raise.py 
try:
    pass
except Exception:
    raise
$ pytype -V 3.5 bare_raise.py 
Traceback (most recent call last):
  File "/Users/bfish/code/pylibofp/venv27/bin/pytype", line 263, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/Users/bfish/code/pylibofp/venv27/bin/pytype", line 232, in main
    return _run_pytype(options)
  File "/Users/bfish/code/pylibofp/venv27/bin/pytype", line 252, in _run_pytype
    options)
  File "/Users/bfish/code/pylibofp/venv27/bin/pytype", line 136, in process_one_file
    options=options)
  File "/Users/bfish/code/pylibofp/venv27/bin/pytype", line 48, in check_pyi
    cache_unknowns=options.cache_unknowns)
  File "/Users/bfish/code/pylibofp/venv27/lib/python2.7/site-packages/pytype/infer.py", line 620, in check_types
    py_src, py_filename, init_maximum_depth, run_builtins)
  File "/Users/bfish/code/pylibofp/venv27/lib/python2.7/site-packages/pytype/vm.py", line 720, in run_program
    node, f_globals, _, _ = self.run_bytecode(node, code, f_globals, f_locals)
  File "/Users/bfish/code/pylibofp/venv27/lib/python2.7/site-packages/pytype/vm.py", line 655, in run_bytecode
    node, return_var = self.run_frame(frame, node)
  File "/Users/bfish/code/pylibofp/venv27/lib/python2.7/site-packages/pytype/vm.py", line 299, in run_frame
    state = self.run_instruction(op, state)
  File "/Users/bfish/code/pylibofp/venv27/lib/python2.7/site-packages/pytype/vm.py", line 256, in run_instruction
    state = bytecode_fn(state, op)
  File "/Users/bfish/code/pylibofp/venv27/lib/python2.7/site-packages/pytype/vm.py", line 2054, in byte_RAISE_VARARGS
    return self.byte_RAISE_VARARGS_PY3(state, op)
  File "/Users/bfish/code/pylibofp/venv27/lib/python2.7/site-packages/pytype/vm.py", line 2048, in byte_RAISE_VARARGS_PY3
    return self.do_raise(state, exc, cause)
  File "/Users/bfish/code/pylibofp/venv27/lib/python2.7/site-packages/pytype/vm.py", line 437, in do_raise
    exc_type, val, _ = state.last_exception
AttributeError: 'FrameState' object has no attribute 'last_exception'
File: bare_raise.py
```

**Comment by matthiaskramm** [comment]
Thanks for the report!

Yes, I'm afraid our Python 3 support is rather bare-bone, right now. I suspect this is one of many issues.

**Comment by martindemello** [comment]
this works now
