### ISSUE TITLE
creating TypedDicts with TypedDict(...)

### ISSUE THREAD

**Issue by Akuli** [google/pytype#637]
```
from typing_extensions import TypedDict
Foo = TypedDict("Foo", {"a": int})
```

```
Traceback (most recent call last):
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pyi/parser.py", line 428, in parse
    defs = parser_ext.parse(self, src)
pytype.pyi.parser.ParseError: ParseError: syntax error, unexpected '(', expecting DEF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpytype.py", line 24, in run_pytype
    pytype_io.parse_pyi(options)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/io.py", line 65, in wrapper
    return f(*args, **kwargs)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/io.py", line 291, in parse_pyi
    ast = loader.load_file(options.module_name, options.input)
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/load_pytd.py", line 240, in load_file
    ast = parser.parse_file(filename=filename, name=module_name,
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pyi/parser.py", line 1273, in parse_file
    return _Parser(version=python_version, platform=platform).parse(
  File "/home/akuli/typeshed/env/lib/python3.8/site-packages/pytype/pyi/parser.py", line 437, in parse
    raise ParseError(utils.message(e), line=line, filename=self._filename,
pytype.pyi.parser.ParseError:   File: "foo.py", line 2
    Foo = TypedDict("Foo", {"a": int})
                   ^
ParseError: syntax error, unexpected '(', expecting DEF
```

I would like to use this syntax for creating a TypedDict that contains a key named `'in'`. I can't do

```
class Foo(TypedDict):
    in: Bar
```

because that's invalid syntax.

**Comment by rchen152** [comment]
We'll probably have to special-case TypedDict the same way we do NamedTuple.
