### ISSUE TITLE
Install Failing with AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by roopeshvs** [google/pytype#662]
```
> pip install pytype
Collecting pytype
  Using cached pytype-2020.8.28.tar.gz (1.6 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\ACER\AppData\Local\Temp\pip-build-env-d082hvm3\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' ninja wheel
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\python38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\python38\lib\site-packages\pip\__main__.py", line 26, in <module>
      sys.exit(_main())
    File "c:\python38\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "c:\python38\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "c:\python38\lib\site-packages\pip\_internal\commands\install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "c:\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "c:\python38\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "c:\python38\lib\site-packages\pip\_vendor\requests\__init__.py", line 125, in <module>
      from . import utils
    File "c:\python38\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
      from . import certs
    File "c:\python38\lib\site-packages\pip\_vendor\requests\certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "c:\python38\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1, in <module>
      from .core import contents, where
    File "c:\python38\lib\site-packages\pip\_vendor\certifi\core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "c:\python38\lib\site-packages\typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "c:\python38\lib\site-packages\typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user 
--prefix 'C:\Users\ACER\AppData\Local\Temp\pip-build-env-d082hvm3\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' ninja wheel Check the logs for full command output.
```
**Environment**
Windows 10 v. 1909
Python 3.8.3

**Comment by rchen152** [comment]
Unfortunately, we don't have the resources to support Windows at the moment. You can try using WSL: https://github.com/google/pytype#installing-on-wsl.

**Comment by Jegp** [comment]
I'm experiencing the same issue on Ubuntu 20.04, Python v. 3.8.2, Pip v. 20.2.2:
```bash
$ pip install pytype        
Collecting pytype                         
  Using cached pytype-2020.8.28.tar.gz (1.6 MB)               
  Installing build dependencies ... error                                                                                                                                                                     [0/854]
  ERROR: Command errored out with exit status 1:                                                                                                                                                                     
   command: /home/jens/.venvs/norse/bin/python3 /home/jens/.venvs/norse/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gothvvpc/overlay --no-warn-script-location -
-no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' ninja wheel
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main 
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 125, in <module>
      from . import utils
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/usr/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/home/jens/.venvs/norse/lib/python3.8/site-packages/typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/jens/.venvs/norse/bin/python3 /home/jens/.venvs/norse/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gothvvpc/
overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' ninja wheel Check the logs for full command output.

**Comment by rchen152** [comment]
I'm out of office until Tuesday, but I'll look into this when I get back.

**Comment by roopeshvs** [comment]
Running
```pip uninstall typing```
before installing pytype fixes this.

This is because
> Typing – Type Hints for Python
> This is a backport of the standard library typing module to Python versions older than 3.5. 
> NOTE: in Python 3.5 and later, the typing module lives in the stdlib, and installing this package has NO EFFECT, because stdlib takes higher precedence than the installation directory.

Refer: https://pypi.org/project/typing/

**Comment by Jegp** [comment]
> Running
> `pip uninstall typing`
> before installing pytype fixes this.

Indeed it does! Thanks for the simple fix! :-)
I guess the issue can be closed?

**Comment by rchen152** [comment]
Thanks for figuring this out! I double-checked that pytype does not install the `typing` package, so I agree this issue can be closed.
