### ISSUE TITLE
Exception in pytype: 'set' object has no attribute 'extend'

### ISSUE THREAD

**Issue by manueljacob** [google/pytype#669]
## How to reproduce

- Download https://www.mercurial-scm.org/release/mercurial-5.5.1.tar.gz
- `tar xaf mercurial-5.5.1.tar.gz`
- `cd mercurial-5.5.1`
- `pytype -V "3.7" mercurial/win32.py`

## Expected result

In `.pytype/pyi`, there’s no pyi file containing “'# Caught error'”.

## Actual result

`.pytype/pyi/mercurial/win32.pyi` contains:

```
from typing import Any
def __getattr__(name: Any) -> Any: ...
# Caught error in pytype: 'set' object has no attribute 'extend'
# Traceback (most recent call last):
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/io.py", line 156, in check_or_generate_pyi
#     errorlog, result, ast = generate_pyi(
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/io.py", line 113, in generate_pyi
#     errorlog, (mod, builtins) = _call(
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/io.py", line 66, in wrapper
#     return f(*args, **kwargs)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/io.py", line 79, in _call
#     return errorlog, analyze_types(
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/analyze.py", line 695, in infer_types
#     tracer.exitpoint = tracer.analyze(loc, defs, maximum_depth)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/analyze.py", line 433, in analyze
#     return self.analyze_toplevel(node, defs)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/analyze.py", line 408, in analyze_toplevel
#     new_node = self.analyze_function(node, value)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/analyze.py", line 385, in analyze_function
#     node2 = self.maybe_analyze_method(node1, val)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/analyze.py", line 181, in maybe_analyze_method
#     node, _ = self.call_function_with_args(node, val, args)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/analyze.py", line 143, in call_function_with_args
#     new_node, ret = self.call_function_in_frame(node, fvar, *args)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/analyze.py", line 152, in call_function_in_frame
#     state, ret = self.call_function_with_state(
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/vm.py", line 1019, in call_function_with_state
#     node, ret = self.call_function(state.node, funcu, function.Args(
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/vm.py", line 1057, in call_function
#     new_node, one_result = func.call(node, funcv, args)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/abstract.py", line 3354, in call
#     node2, ret = self.vm.run_frame(frame, node, annotated_locals)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/vm.py", line 332, in run_frame
#     state = self.run_instruction(op, state)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/vm.py", line 288, in run_instruction
#     state = bytecode_fn(state, op)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/vm.py", line 2209, in byte_LOAD_ATTR
#     state, val = self.load_attr(state, obj, name)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/vm.py", line 1428, in load_attr
#     node, result, errors = self._retrieve_attr(state.node, obj, attr)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/vm.py", line 1398, in _retrieve_attr
#     node2, attr_var = self.attribute_handler.get_attribute(
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/attribute.py", line 59, in get_attribute
#     return self._get_instance_attribute(node, obj, name, valself)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/attribute.py", line 228, in _get_instance_attribute
#     return self._get_attribute(node, obj, obj.cls, name, valself)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/attribute.py", line 279, in _get_attribute
#     attr = self._filter_var(node, attr)
#   File "/home/manu/.local/lib/python3.8/site-packages/pytype/attribute.py", line 444, in _filter_var
#     bindings.extend(var_bindings)
# AttributeError: 'set' object has no attribute 'extend'
```

**Comment by rchen152** [comment]
I think fixing this is as simple as converting the set to a list here: https://github.com/google/pytype/blob/1ba0d20b0e7db625502f3d03776647fd91c7847c/pytype/typegraph/cfg.py#L383. (I was a little surprised that we're still using the pure-Python implementation of the cfg!)
