### ISSUE TITLE
How does -c work?

### ISSUE THREAD

**Issue by gvanrossum** [google/pytype#8]
The command line help says
```
  -c, --check           Verify against existing "output" pytd files.
```
But I don't understand how to use it. Suppose I have basic.py containing some self-contained code (no imports), I can generate basic.pytd by running
```
pytd basic.py:basic.pytd
```
Now suppose I edit basic.py -- the `-c` options suggests that I could verify that the modified basic.py still conforms to the original basic.pytd, but all I get is errors:
```
$ pytype -c basic.py
Traceback (most recent call last):
  File "/Users/guido/v/bin/pytype", line 202, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/Users/guido/v/bin/pytype", line 196, in main
    ret = process_one_file(input_filename, output_filename, options)
  File "/Users/guido/v/bin/pytype", line 146, in process_one_file
    options=options)
  File "/Users/guido/v/bin/pytype", line 32, in check_pytd
    with open(output_filename, "r") as fi:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
or
```
$ pytype -c basic.py:basic.pytd
Traceback (most recent call last):
  File "/Users/guido/v/bin/pytype", line 202, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/Users/guido/v/bin/pytype", line 196, in main
    ret = process_one_file(input_filename, output_filename, options)
  File "/Users/guido/v/bin/pytype", line 146, in process_one_file
    options=options)
  File "/Users/guido/v/bin/pytype", line 45, in check_pytd
    maximum_depth=(1 if options.quick else None))
TypeError: check_types() got an unexpected keyword argument 'import_pytd_ext'
```

**Comment by matthiaskramm** [comment]
This isn't implemented yet. (You'd think the --help output would point that out! D'oh.)

Will leave this bug open, since obviously this is something that needs to be done.

**Comment by matthiaskramm** [comment]
Fixed. The commands
```
  pytype -c file.py:file.pyi
```
and
```
  pytype -c file.py
```
should work now. (To which degree they do something useful is debatable, but they will do some basic checking)
