### ISSUE TITLE
pytype scripts can no longer be run globally

### ISSUE THREAD

**Issue by rchen152** [google/pytype#83]
After the switch from distutils to setup, I can no longer use just `pytype` or `pytype-all` to run the corresponding script, I have to do (assuming I'm in my local copy of the pytype repo) `./scripts/pytype`.  Otherwise, I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/pytype", line 4, in <module>
    __import__('pkg_resources').run_script('pytype==0.2', 'pytype')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1492, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'pytype'
```
Possibly related to https://stackoverflow.com/questions/30221573/pythons-setup-py-installed-cli-script-doesnt-allow-importing-same-module.

**Comment by rchen152** [comment]
Weird, everything works fine in a virtualenv. Probably an issue with my setup then.

**Comment by rchen152** [comment]
So I more or less figured out what was going on - I had pytype-0.2.egg-info installed in the right place, but there was another file already there with the same name, as well as one called pytype.egg-link (cruft from previous pytype installations, I suppose).  I deleted those and all is well again.
