### ISSUE TITLE
Failing with a CompileError due to `-S` being passed to the compilation interpreter

### ISSUE THREAD

**Issue by gpshead** [google/pytype#84]
Using the README.md install instructions-ish but within a virtualenv using Python 3 (3.6.5).

```
/pytype$ virtualenv -p python3.6 venv
/pytype$ venv/bin/pip install pyyaml six
/pytype$ venv/bin/pip install .
```

```shell
greg@europa:~/oss/write_new_bugs$ pytype -V 3.6 thing.py 
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/home/greg/oss/pytype/venv/lib/python3.6/imp.py", line 23, in <module>
    from importlib import util
  File "/home/greg/oss/pytype/venv/lib/python3.6/importlib/util.py", line 13, in <module>
    from contextlib import contextmanager
ModuleNotFoundError: No module named 'contextlib'
Traceback (most recent call last):
  File "/home/greg/oss/pytype/venv/bin/pytype", line 294, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/home/greg/oss/pytype/venv/bin/pytype", line 260, in main
    return _run_pytype(options)
  File "/home/greg/oss/pytype/venv/bin/pytype", line 283, in _run_pytype
    options)
  File "/home/greg/oss/pytype/venv/bin/pytype", line 135, in process_one_file
    loader=loader)
  File "/home/greg/oss/pytype/venv/bin/pytype", line 58, in check_pyi
    deep=not options.main_only)
  File "/home/greg/oss/pytype/venv/lib/python3.6/site-packages/pytype/analyze.py", line 586, in check_types
    loc, defs = tracer.run_program(src, filename, init_maximum_depth)
  File "/home/greg/oss/pytype/venv/lib/python3.6/site-packages/pytype/vm.py", line 664, in run_program
    code = self.compile_src(src, filename=filename)
  File "/home/greg/oss/pytype/venv/lib/python3.6/site-packages/pytype/vm.py", line 635, in compile_src
    filename=filename, mode=mode)
  File "/home/greg/oss/pytype/venv/lib/python3.6/site-packages/pytype/pyc/pyc.py", line 154, in compile_src
    src, filename, python_version, python_exe, mode)
  File "/home/greg/oss/pytype/venv/lib/python3.6/site-packages/pytype/pyc/pyc.py", line 78, in compile_src_string_to_pyc_string
    assert p.poll() == 0, "Child process failed"
AssertionError: Child process failed
File: thing.py
```

The workaround appears to be removing the `'-S'` command line flag being passed to the Python interpreter to compile the code in `pytype/pyc.py` `compile_src_string_to_pyc_string`.

**Comment by gpshead** [comment]
I blame the older virtualenv setuff. I should use venv.  But the error message is entirely mysterious so hopefully this issue will be found my anyone else running into this.

I need to get used to using `venv`.
