### ISSUE TITLE
Property and _typeshed.Self

### ISSUE THREAD

**Issue by srittau** [google/pytype#952]
Please consider the following stub file:

```python
from _typeshed import Self

from typing import TypeVar

Self2 = TypeVar("Self2")

class Foo:
    def method(self: Self) -> Self: ...  # Works
    @property
    def prop(self: Self) -> Self: ...  # Error
    @property
    def prop2(self: Self2) -> Self2: ...  # Works
```

When checking this from a typeshed directory with pytype 2021.05.25, I get the following output:

```
$ TYPESHED_HOME=. pytype-single --parse-pyi foo.pyi 
Traceback (most recent call last):
  File "/home/srittau/Projekte/typeshed/.venv-3.9/bin/pytype-single", line 8, in <module>
    sys.exit(main())
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/single.py", line 82, in main
    return _run_pytype(options)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/single.py", line 90, in _run_pytype
    unused_ast = io.parse_pyi(options)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/io.py", line 63, in wrapper
    return f(*args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/io.py", line 286, in parse_pyi
    ast = loader.load_file(options.module_name, options.input)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/load_pytd.py", line 500, in load_file
    return self._process_module(module_name, filename, mod_ast)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/load_pytd.py", line 524, in _process_module
    module.ast = module.ast.Visit(visitors.AdjustTypeParameters())
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/parse/node.py", line 90, in Visit
    return _Visit(self, visitor, *args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/parse/node.py", line 108, in _Visit
    return _VisitNode(node, visitor, *args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/parse/node.py", line 200, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/parse/node.py", line 159, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/parse/node.py", line 200, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/parse/node.py", line 159, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/parse/node.py", line 200, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/parse/node.py", line 200, in _VisitNode
    new_child = _VisitNode(child, visitor, *args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/parse/node.py", line 213, in _VisitNode
    new_node = visitor.Visit(new_node, *args, **kwargs)
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/base_visitor.py", line 197, in Visit
    return self.visit_functions[node.__class__.__name__](
  File "/home/srittau/Projekte/typeshed/.venv-3.9/lib/python3.9/site-packages/pytype/pytd/visitors.py", line 1532, in VisitTypeParameter
    raise ContainerError("Unbound type parameter %s in %s" % (
pytype.pytd.visitors.ContainerError: Unbound type parameter Self in foo.Foo.prop
```

This is only a problem when importing `Self` from `_typeshed` and using it for a `@property`. Either defining it inline or using the imported `Self` for a regular method works fine.

**Comment by rchen152** [comment]
This is caused by some of the parsing code only recognizing TypeVars that are defined in the current stub: http://google3/third_party/py/pytype/pyi/definitions.py?l=260-263&rcl=373679585. Fix incoming.
